# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/gabriel/Documents/c_project

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/gabriel/Documents/c_project

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gabriel/Documents/c_project/CMakeFiles /home/gabriel/Documents/c_project//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gabriel/Documents/c_project/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named TI_301_PJT

# Build rule for target.
TI_301_PJT: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TI_301_PJT
.PHONY : TI_301_PJT

# fast build rule for target.
TI_301_PJT/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TI_301_PJT.dir/build.make CMakeFiles/TI_301_PJT.dir/build
.PHONY : TI_301_PJT/fast

#=============================================================================
# Target rules for targets named part1

# Build rule for target.
part1: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 part1
.PHONY : part1

# fast build rule for target.
part1/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/part1.dir/build.make CMakeFiles/part1.dir/build
.PHONY : part1/fast

#=============================================================================
# Target rules for targets named part2

# Build rule for target.
part2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 part2
.PHONY : part2

# fast build rule for target.
part2/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/part2.dir/build.make CMakeFiles/part2.dir/build
.PHONY : part2/fast

#=============================================================================
# Target rules for targets named part3

# Build rule for target.
part3: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 part3
.PHONY : part3

# fast build rule for target.
part3/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/part3.dir/build.make CMakeFiles/part3.dir/build
.PHONY : part3/fast

hasse.o: hasse.c.o
.PHONY : hasse.o

# target to build an object file
hasse.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TI_301_PJT.dir/build.make CMakeFiles/TI_301_PJT.dir/hasse.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/part1.dir/build.make CMakeFiles/part1.dir/hasse.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/part2.dir/build.make CMakeFiles/part2.dir/hasse.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/part3.dir/build.make CMakeFiles/part3.dir/hasse.c.o
.PHONY : hasse.c.o

hasse.i: hasse.c.i
.PHONY : hasse.i

# target to preprocess a source file
hasse.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TI_301_PJT.dir/build.make CMakeFiles/TI_301_PJT.dir/hasse.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/part1.dir/build.make CMakeFiles/part1.dir/hasse.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/part2.dir/build.make CMakeFiles/part2.dir/hasse.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/part3.dir/build.make CMakeFiles/part3.dir/hasse.c.i
.PHONY : hasse.c.i

hasse.s: hasse.c.s
.PHONY : hasse.s

# target to generate assembly for a file
hasse.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TI_301_PJT.dir/build.make CMakeFiles/TI_301_PJT.dir/hasse.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/part1.dir/build.make CMakeFiles/part1.dir/hasse.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/part2.dir/build.make CMakeFiles/part2.dir/hasse.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/part3.dir/build.make CMakeFiles/part3.dir/hasse.c.s
.PHONY : hasse.c.s

main.o: main.c.o
.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TI_301_PJT.dir/build.make CMakeFiles/TI_301_PJT.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i
.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TI_301_PJT.dir/build.make CMakeFiles/TI_301_PJT.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s
.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TI_301_PJT.dir/build.make CMakeFiles/TI_301_PJT.dir/main.c.s
.PHONY : main.c.s

main1.o: main1.c.o
.PHONY : main1.o

# target to build an object file
main1.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/part1.dir/build.make CMakeFiles/part1.dir/main1.c.o
.PHONY : main1.c.o

main1.i: main1.c.i
.PHONY : main1.i

# target to preprocess a source file
main1.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/part1.dir/build.make CMakeFiles/part1.dir/main1.c.i
.PHONY : main1.c.i

main1.s: main1.c.s
.PHONY : main1.s

# target to generate assembly for a file
main1.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/part1.dir/build.make CMakeFiles/part1.dir/main1.c.s
.PHONY : main1.c.s

main2.o: main2.c.o
.PHONY : main2.o

# target to build an object file
main2.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/part2.dir/build.make CMakeFiles/part2.dir/main2.c.o
.PHONY : main2.c.o

main2.i: main2.c.i
.PHONY : main2.i

# target to preprocess a source file
main2.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/part2.dir/build.make CMakeFiles/part2.dir/main2.c.i
.PHONY : main2.c.i

main2.s: main2.c.s
.PHONY : main2.s

# target to generate assembly for a file
main2.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/part2.dir/build.make CMakeFiles/part2.dir/main2.c.s
.PHONY : main2.c.s

main3.o: main3.c.o
.PHONY : main3.o

# target to build an object file
main3.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/part3.dir/build.make CMakeFiles/part3.dir/main3.c.o
.PHONY : main3.c.o

main3.i: main3.c.i
.PHONY : main3.i

# target to preprocess a source file
main3.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/part3.dir/build.make CMakeFiles/part3.dir/main3.c.i
.PHONY : main3.c.i

main3.s: main3.c.s
.PHONY : main3.s

# target to generate assembly for a file
main3.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/part3.dir/build.make CMakeFiles/part3.dir/main3.c.s
.PHONY : main3.c.s

matrix.o: matrix.c.o
.PHONY : matrix.o

# target to build an object file
matrix.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TI_301_PJT.dir/build.make CMakeFiles/TI_301_PJT.dir/matrix.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/part3.dir/build.make CMakeFiles/part3.dir/matrix.c.o
.PHONY : matrix.c.o

matrix.i: matrix.c.i
.PHONY : matrix.i

# target to preprocess a source file
matrix.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TI_301_PJT.dir/build.make CMakeFiles/TI_301_PJT.dir/matrix.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/part3.dir/build.make CMakeFiles/part3.dir/matrix.c.i
.PHONY : matrix.c.i

matrix.s: matrix.c.s
.PHONY : matrix.s

# target to generate assembly for a file
matrix.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TI_301_PJT.dir/build.make CMakeFiles/TI_301_PJT.dir/matrix.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/part3.dir/build.make CMakeFiles/part3.dir/matrix.c.s
.PHONY : matrix.c.s

tarjan.o: tarjan.c.o
.PHONY : tarjan.o

# target to build an object file
tarjan.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TI_301_PJT.dir/build.make CMakeFiles/TI_301_PJT.dir/tarjan.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/part2.dir/build.make CMakeFiles/part2.dir/tarjan.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/part3.dir/build.make CMakeFiles/part3.dir/tarjan.c.o
.PHONY : tarjan.c.o

tarjan.i: tarjan.c.i
.PHONY : tarjan.i

# target to preprocess a source file
tarjan.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TI_301_PJT.dir/build.make CMakeFiles/TI_301_PJT.dir/tarjan.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/part2.dir/build.make CMakeFiles/part2.dir/tarjan.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/part3.dir/build.make CMakeFiles/part3.dir/tarjan.c.i
.PHONY : tarjan.c.i

tarjan.s: tarjan.c.s
.PHONY : tarjan.s

# target to generate assembly for a file
tarjan.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TI_301_PJT.dir/build.make CMakeFiles/TI_301_PJT.dir/tarjan.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/part2.dir/build.make CMakeFiles/part2.dir/tarjan.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/part3.dir/build.make CMakeFiles/part3.dir/tarjan.c.s
.PHONY : tarjan.c.s

utils.o: utils.c.o
.PHONY : utils.o

# target to build an object file
utils.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TI_301_PJT.dir/build.make CMakeFiles/TI_301_PJT.dir/utils.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/part1.dir/build.make CMakeFiles/part1.dir/utils.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/part2.dir/build.make CMakeFiles/part2.dir/utils.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/part3.dir/build.make CMakeFiles/part3.dir/utils.c.o
.PHONY : utils.c.o

utils.i: utils.c.i
.PHONY : utils.i

# target to preprocess a source file
utils.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TI_301_PJT.dir/build.make CMakeFiles/TI_301_PJT.dir/utils.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/part1.dir/build.make CMakeFiles/part1.dir/utils.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/part2.dir/build.make CMakeFiles/part2.dir/utils.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/part3.dir/build.make CMakeFiles/part3.dir/utils.c.i
.PHONY : utils.c.i

utils.s: utils.c.s
.PHONY : utils.s

# target to generate assembly for a file
utils.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TI_301_PJT.dir/build.make CMakeFiles/TI_301_PJT.dir/utils.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/part1.dir/build.make CMakeFiles/part1.dir/utils.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/part2.dir/build.make CMakeFiles/part2.dir/utils.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/part3.dir/build.make CMakeFiles/part3.dir/utils.c.s
.PHONY : utils.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... TI_301_PJT"
	@echo "... part1"
	@echo "... part2"
	@echo "... part3"
	@echo "... hasse.o"
	@echo "... hasse.i"
	@echo "... hasse.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... main1.o"
	@echo "... main1.i"
	@echo "... main1.s"
	@echo "... main2.o"
	@echo "... main2.i"
	@echo "... main2.s"
	@echo "... main3.o"
	@echo "... main3.i"
	@echo "... main3.s"
	@echo "... matrix.o"
	@echo "... matrix.i"
	@echo "... matrix.s"
	@echo "... tarjan.o"
	@echo "... tarjan.i"
	@echo "... tarjan.s"
	@echo "... utils.o"
	@echo "... utils.i"
	@echo "... utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

